# Generated by Django 3.0.5 on 2020-05-18 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoalsList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Goal', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='GoalModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Check', models.CharField(choices=[('Done', 'Done'), ("Didn't do", "Didn't do")], default='some', max_length=50)),
                ('Goals', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='constapp.GoalsList')),
            ],
        ),
        migrations.CreateModel(
            name='DateModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='constapp.GoalsList')),
            ],
        ),
    ]
