# Generated by Django 3.0.5 on 2020-05-19 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Check', models.CharField(choices=[('Done', 'Done'), ("Didn't do", "Didn't do")], default='some', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(auto_now=True)),
                ('Check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='constapp.Check')),
            ],
        ),
        migrations.CreateModel(
            name='Goals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Goal', models.CharField(max_length=50)),
                ('Date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='constapp.Date')),
            ],
        ),
        migrations.CreateModel(
            name='JoinModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GoalList', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='constapp.Goals')),
            ],
        ),
    ]
