# Generated by Django 3.0.5 on 2020-05-19 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constapp', '0002_check_date_goals_joinmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='Date',
            field=models.DateField(),
        ),
    ]
